# Generated by Django 5.2.6 on 2025-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listfastapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlisting",
            name="listing_type",
            field=models.CharField(
                choices=[
                    ("Single", "Single"),
                    ("Multi", "Multi"),
                    ("Bundle", "Bundle"),
                ],
                default="Single",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userlisting",
            name="vat_rate",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
