# Generated by Django 5.2.6 on 2025-10-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listfastapp", "0002_creditpackage_creditpurchase_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplan",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
