# Generated by Django 5.2.6 on 2025-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listfastapp", "0003_userplan_stripe_subscription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userplan",
            name="stripe_payment_intent_id_initial",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
