# Generated by Django 5.2.6 on 2025-10-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listfastapp", "0004_userplan_stripe_payment_intent_id_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userplan",
            name="stripe_payment_intent_id_initial",
        ),
    ]
