from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('ebay-login/', views.eBayLoginView.as_view(), name='ebay-login'),
    path('callback/', views.eBayCallbackView.as_view(), name='ebay-callback'),
    path('image-enhancement/', views.ImageEnhancementView.as_view(), name='image-enhancement'),
    path('display-profile/', views.DisplayProfileView.as_view(), name='display-profile'),
    path('ebay-auth/', views.eBayAuthView.as_view(), name='ebay-auth'),
    path('single-item-listing/', views.SingleItemListingView.as_view(), name='single-item-listing'),
    path('success/', views.SuccessView.as_view(), name='success'),
    path('services/', views.ServicesView.as_view(), name='services'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('auth-status/', views.AuthStatusView.as_view(), name='auth-status'),
    path('publish-item/', views.PublishItemView.as_view(), name='publish-item'),
    path('total-listings/', views.TotalListingsView.as_view(), name='total-listings'),
    path('user-stats/', views.UserStatsView.as_view(), name='user-stats'),
    path('my-listings/', views.MyListingsView.as_view(), name='my-listings'),
    path('upload-profile-image/', views.UploadProfileImageView.as_view(), name='upload-profile-image'),
    path('send-password-otp/', views.SendPasswordChangeOTPView.as_view(), name='send-password-otp'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change-password'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('verify-otp/', views.VerifyOTPView.as_view(), name='verify-otp'),
    path('resend-otp/', views.ResendOTPView.as_view(), name='resend-otp'),
    path('revoke-ebay-auth/', views.RevokeeBayAuthView.as_view(), name='revoke-ebay-auth'),
    path('format-description/', views.FormatDescriptionView.as_view(), name='format-description'),
    path('enhance-image/', views.EnhanceImageView.as_view(), name='enhance-image'),
    path('fetch-address-imageprofile/', views.FetchAddressImageProfileView.as_view(), name='fetch-address-imageprofile'),
    path('preview-item/', views.PreviewItemView.as_view(), name='preview-item'),
    path('publish-item-from-preview/', views.PublishItemFromPreviewView.as_view(), name='publish-item-from-preview'),
]
