from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index_view, name='index'),
    path('profile/', views.profile_view, name='profile'),
    path('image-enhancement/', views.image_enhancement_view, name='image-enhancement'),
    path('display-profile/', views.display_profile_view, name='display-profile'),
    path('pricing/', views.pricing_view, name='pricing'),
    path('ebay-auth/', views.ebay_auth_view, name='ebay-auth'),
    path('success/', views.success_view, name='success'),
    path('single-listing-success/', views.single_listing_success_view, name='single-listing-success'),
    path('services/', views.services_view, name='services'),
    path('callback/', views.ebay_callback_view, name='ebay-callback'),
    path('ebay-login/', views.ebay_login_view, name='ebay-login'),
    path('single-item-listing/', views.single_item_listing_view, name='single-item-listing'),
    path('multi-item-listing/', views.multi_item_listing_view, name='multi-item-listing'),
    path('bundle-item-listing/', views.bundle_listing_view, name='bundle-listing'),
    path('logout/', views.logout_view, name='logout'),
    path('about/', views.about_us, name='about-us'),
    path('blogs/', views.blogs_resources, name='blogs-resources'),
    path('features/',views.features, name='features'),
    path('contact/',views.contact, name='contact'),
    path('legal/',views.legal, name='legal'),
    path('faq/',views.faq, name='faq'),


    path('api/login/', views.LoginAPIView.as_view(), name='api-login'),
    path('api/profile/', views.ProfileAPIView.as_view(), name='api-profile'),
    path('api/auth-status/', views.AuthStatusAPIView.as_view(), name='api-auth-status'),
    path('api/total-listings/', views.TotalListingsAPIView.as_view(), name='api-total-listings'),
    path('api/user-stats/', views.UserStatsAPIView.as_view(), name='api-user-stats'),
    path('api/my-listings/', views.MyListingsAPIView.as_view(), name='api-my-listings'),
    path('api/fetch-address-imageprofile/', views.FetchAddressImageProfileAPIView.as_view(), name='api-fetch-address-imageprofile'),
    path('api/upload-profile-image/', views.UploadProfileImageAPIView.as_view(), name='api-upload-profile-image'),
    path('api/send-password-otp/', views.SendPasswordChangeOTPAPIView.as_view(), name='api-send-password-otp'),
    path('api/change-password/', views.ChangePasswordAPIView.as_view(), name='api-change-password'),
    path('api/signup/', views.SignupAPIView.as_view(), name='api-signup'),
    path('api/verify-otp/', views.VerifyOTPAPIView.as_view(), name='api-verify-otp'),
    path('api/resend-otp/', views.ResendOTPAPIView.as_view(), name='api-resend-otp'),
    path('api/revoke-ebay-auth/', views.RevokeeBayAuthAPIView.as_view(), name='revoke-ebay-auth'),
    path('api/format-description/', views.FormatDescriptionAPIView.as_view(), name='api-format-description'),
    path('api/enhance-image/', views.EnhanceImageAPIView.as_view(), name='api-enhance-image'),
    path('api/single-item-listing/', views.SingleItemListingAPIView.as_view(), name='api-single-item-listing'),
    path('api/task-status/', views.TaskStatusAPIView.as_view(), name='api-task-status'),
    path('api/my-tasks/', views.MyTasksAPIView.as_view(), name='api-my-tasks'),
    path('api/multipack-listing/', views.MultipackListingAPIView.as_view(), name='api-multipack-listing'),
    path('api/bundle-listing/', views.BundleListingAPIView.as_view(), name='api-bundle-listing'),
    path('api/usage/', views.UsageStatusAPIView.as_view(), name='api-usage-local'),
    path('api/plan-status/', views.UserPlanStatusAPIView.as_view(), name='api-plan-status'),
    path('api/request-refund/', views.RequestRefundAPIView.as_view(), name='api-request-refund'),
    path('api/create-checkout-session/', views.CreateCheckoutSessionAPIView.as_view(), name='api-create-checkout-local'),
    path('api/stripe-webhook/', views.StripeWebhookAPIView.as_view(), name='api-stripe-webhook'),
    path('api/subscribe-mailchimp/', views.SubscribeToMailchimpAPIView.as_view(), name='api-subscribe-mailchimp'),
]